# Generated by Django 5.1.7 on 2025-04-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('SALESMAN', 'Salesman'), ('CLERK', 'Clerk'), ('DELIVERYMAN', 'Deliveryman')], default='DELIVERYMAN', max_length=20),
        ),
    ]
