# Generated by Django 5.1.7 on 2025-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('SALESMAN', 'Salesman'), ('CLERK', 'Clerk'), ('DELIVERYMAN', 'Deliveryman'), ('CEO', 'CEO')], default='DELIVERYMAN', max_length=20),
        ),
    ]
