# Generated by Django 5.1.7 on 2025-05-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='annual_leave_days',
            field=models.FloatField(default=7.0),
        ),
    ]
