# Generated by Django 5.1.7 on 2025-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeprofile_annual_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bonus_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
