# Generated by Django 5.1.7 on 2025-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='year_end_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
