# Generated by Django 5.2.5 on 2025-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeeprofile_year_end_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this employee should be treated as active.'),
        ),
    ]
