# Generated by Django 5.1.7 on 2025-05-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationitem',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2, null=True),
        ),
    ]
