# Generated by Django 5.2.5 on 2025-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_vacationitem_half_day_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationitem',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave')], default='Annual Leave', max_length=20, null=True),
        ),
    ]
