# Generated by Django 5.1.7 on 2025-04-22 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('client_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=10)),
                ('new_client', models.BooleanField(default=False)),
                ('orders', models.TextField(blank=True)),
                ('tel_orders', models.TextField(blank=True)),
                ('samples', models.TextField(blank=True)),
                ('new_product_intro', models.TextField(blank=True)),
                ('old_product_followup', models.TextField(blank=True)),
                ('delivery_time_update', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
