# Generated by Django 5.1.7 on 2025-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportentry',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportentry',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportentry',
            name='time_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
