# Generated by Django 5.2.5 on 2025-08-29 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportentry_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['date'], name='report_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['salesman'], name='report_salesman_idx'),
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['salesman', 'date'], name='report_salesman_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['-date', '-created_at'], name='report_date_created_idx'),
        ),
    ]
